// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBmB7_kwCPi6LWAD_xkXi1T1eNNbdCK2js',
    appId: '1:455168300450:web:07716c55b7a2edb3e14efb',
    messagingSenderId: '455168300450',
    projectId: 'test-pub-sub-392102',
    authDomain: 'test-pub-sub-392102.firebaseapp.com',
    storageBucket: 'test-pub-sub-392102.appspot.com',
    measurementId: 'G-D8R6S22042',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCsunI6YpYRuyGUDvwmGpCwRY9Ku3lf2A4',
    appId: '1:455168300450:android:4738ea490bb1596ce14efb',
    messagingSenderId: '455168300450',
    projectId: 'test-pub-sub-392102',
    storageBucket: 'test-pub-sub-392102.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBB3LGh9PLkjMZDIbdIqTwu0qAZOCgSjbg',
    appId: '1:455168300450:ios:b1bdd7fc6f5b3c84e14efb',
    messagingSenderId: '455168300450',
    projectId: 'test-pub-sub-392102',
    storageBucket: 'test-pub-sub-392102.appspot.com',
    iosClientId: '455168300450-nmsfeog7nbmpu4fa53hrpe2k52i5v0oj.apps.googleusercontent.com',
    iosBundleId: 'com.example.notify',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBB3LGh9PLkjMZDIbdIqTwu0qAZOCgSjbg',
    appId: '1:455168300450:ios:3f7ecb9f585459b9e14efb',
    messagingSenderId: '455168300450',
    projectId: 'test-pub-sub-392102',
    storageBucket: 'test-pub-sub-392102.appspot.com',
    iosClientId: '455168300450-ulldfoocrm83se9hmikjqq9th29kp0fq.apps.googleusercontent.com',
    iosBundleId: 'com.example.notify.RunnerTests',
  );
}
